version: '3'

services:

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    depends_on:
      - mysql
      - redis
      - mailpit
    environment:
      CONTAINER_ROLE: app
      CONTAINER_MODE: automatic
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    ports:
      - "8000:8000"
    networks:
      - laravel

  horizon:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    depends_on:
      - app
    environment:
      CONTAINER_ROLE: horizon
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - laravel

  scheduler:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    depends_on:
      - app
    environment:
      CONTAINER_ROLE: scheduler
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - laravel

  mysql:
    image: mysql/mysql-server:8.0
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
    ports:
      - '${FORWARD_MYSQL_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./.docker/volumes/mysql:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:latest
    restart: always
    command: --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./.docker/volumes/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - '6379:6379'
    environment:
      REDIS_PORT: 6379
    networks:
      - laravel

  mailpit:
    image: axllent/mailpit:latest
    restart: always
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
