apiVersion: v1
kind: ConfigMap
metadata:
  name: projectname-config
  namespace: projectname
data:
  APP_NAME: "Filament K8s Demo"
  APP_ENV: local
  APP_KEY: base64:41O0zXX5PDtUAfz2FBXAKG1LRPp9lUzy+kZxTpu3wKo=
  APP_DEBUG: "true"
  APP_URL: http://localhost:8000

  LOG_CHANNEL: stdout
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: debug

  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_DATABASE: workshop_k8s
  DB_USERNAME: workshop_k8s
  DB_PASSWORD: secret

  BROADCAST_DRIVER: log
  CACHE_DRIVER: redis
  FILESYSTEM_DISK: local
  QUEUE_CONNECTION: redis
  SESSION_DRIVER: redis
  SESSION_LIFETIME: "120"

  MEMCACHED_HOST: "127.0.0.1"

  REDIS_HOST: redis
  REDIS_PASSWORD: secret
  REDIS_PORT: "6379"

  MAIL_MAILER: smtp
  MAIL_HOST: mailpit
  MAIL_PORT: "1025"
  MAIL_USERNAME: "null"
  MAIL_PASSWORD: "null"
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: "hello@example.com"
  MAIL_FROM_NAME: "${APP_NAME}"
